name: freyja-cryptic
channels:
  - bioconda
  - conda-forge
dependencies:
  - freyja=1.5.1
  - pip:
      - git+https://github.com/outbreak-info/python-outbreak-info.git@new_docs_2
      - frozendict
      - pyyaml
      - tqdm